import {Inter} from 'next/font/google'
import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={'bg-[#F8C8DC] h-screen w-screen flex flex-col items-center justify-between'}>
            {children}
        </div>
        </body>
        </html>
    )
}
